#+title: Dilemmas of mathematics teaching
#+date: <2022-12-27 20:29>
#+description: 
#+filetags: articles
A little while ago, Fraser Gobede and I co-authored an article entitled, “Studying dilemmas of mathematics teaching in Southern Africa”. This article was inspired by the works of scholars like Magdalene Lampert and Deborah Ball. Instead of focusing on how well teachers perform, or what knowledge teachers have (or are lacking), these scholars investigate the work of teaching mathematics and its entailments. In the article we focus on the concept of “dilemmas”, which Magdalene Lampert wrote about several decades ago. She considered the teacher as a “dilemma-manager” and aimed at understanding the dilemmas that teachers were faced with in their teaching of mathematics.

In this article, we develop an argument about the promise of focusing on dilemmas of teaching mathematics in the Southern African context, where there tends to be a strong focus on what knowledge teachers are lacking, and many studies have a deficit view of teachers. We suggest that shifting the focus toward identifying and exploring dilemmas of mathematics teaching may provide a more productive approach. Below is the abstract of our article:

#+begin_quote
Background: Learners in many countries in sub-Saharan Africa are underperforming in important subjects such as mathematics, and research in these contexts tends to focus on the lack of resources, insufficient teacher knowledge or poor quality in teaching as explanatory factors. This study has taken a different approach.

Aim: The study aimed at exploring how analysis of dilemmas that teachers encounter in the work of teaching mathematics may provide a productive approach to studying mathematics teaching in the African context.

Setting: The study was conducted in a rural Malawian Grade 1 classroom, where a teacher was teaching arithmetical notation to young learners.

Methods: A case study approach was applied, and data were gathered through video observations and interviews. Inductive analysis of observation data was applied to identify and unpack dilemmas of mathematics teaching.

Results: Two inherent dilemmas of the complex work of teaching mathematics have been identified and discussed. One dilemma was to decide when and how to present arithmetical notations in different modalities without losing the mathematical meaning. A second dilemma was to decide how to deal with unexpected learner errors while maintaining the planned focus of the lesson.

Conclusion: Considering dilemmas of teaching shifts the emphasis from evaluating the teacher to understanding and developing shared understanding of teaching as professional practice.

Contribution: The suggested shift in focus acknowledges the challenges of the local context without reverting to deficit views, and it contributes to developing a shared professional language.
#+end_quote

* Reference
Gobede, F., & Mosvold, R. (2022). Studying dilemmas of mathematics teaching in Southern Africa.  /African Journal of Teacher Education and Development, 1/ (1), a4. https://doi.org/10.4102/ajoted.v1i1.4
