#+title: Literature review on discussion
#+date: <2024-08-06 14:35>
#+description: 
#+filetags: articles

It has been a while since [[https://www.icme14.org/static/en/index.html?v=28960409819][ICME-14]], but the proceedings have now finally been published. In volume II, among the invited lectures, is my review of literature on discussion in mathematics teaching. Based on a systematic search in Eric, and on searches in major journals of mathematics education, I reviewed 72 peer-reviewed articles on discussion in mathematics teaching, which were published between 2000 and 2020. Below is the abstract:

#+begin_quote
For decades, reformers have emphasized discussion over recitation and lecture. Yet, traditional communication patterns are still dominant in mathematics classrooms internationally. In an effort to better understand this challenge, the present study investigates patterns and contributions of research on discussion in mathematics teaching. Based on systematic search in the Eric database, and in selected journals of mathematics education, 72 studies were reviewed. Based on analysis and discussion of the reviewed studies, it is suggested to develop conceptual clarity and include definitions of core terms like discussion, to consider alternative methods for studying discussion in teaching, and to consider shifting the focus from teacher actions to the entailments of the work of leading mathematical discussions.
#+end_quote

The citation to the paper is:

Mosvold, R. (2024). Research on discussion in mathematics teaching: A review of literature from 2000 to 2020. In J. Wang (Ed.), Proceedings of the 14th International Congress on Mathematical Education (Volume II: Invited Lectures), (pp. 473–488). World Scientific Publishing House. https://doi.org/10.1142/9789811287183_0032
